import {expect, test} from '@playwright/test'

test.skip(!process.env.REAL_E2E, 'Requer Docker com banco demo; valida o Admin e recusa de clima sem LLM')

test('política real: Admin apresenta prompts e cliente recebe recusa de clima', async ({browser}) => {
  const adminContext = await browser.newContext()
  const admin = await adminContext.newPage()
  await admin.goto('/login')
  await admin.getByLabel('Usuário').fill('Admin')
  await admin.getByLabel('Senha').fill('Admin')
  await admin.getByRole('button', {name:'Entrar', exact:true}).click()
  await expect(admin).toHaveURL(/\/admin/)
  await admin.getByRole('button', {name:'Agentes e segurança', exact:true}).click()
  await admin.locator('summary').filter({hasText:'ROUTER'}).click()
  await expect(admin.locator('.agent-source pre').first()).toContainText('cotação/conversão de câmbio')
  await expect(admin.locator('body')).not.toContainText('GETNET-GUARD-CANARY-9F3A')
  await admin.screenshot({path:'../docs/evidence/agent-policy/admin-prompts.png', fullPage:true})
  await admin.getByRole('button', {name:'Regras de guardrails'}).click()
  await admin.locator('summary').filter({hasText:'Fontes'}).click()
  await expect(admin.locator('.agent-source[open] pre')).toContainText('bcb.gov.br')
  await admin.screenshot({path:'../docs/evidence/agent-policy/admin-guardrails.png', fullPage:true})

  const context = await browser.newContext()
  const customer = await context.newPage()
  await customer.goto('/')
  await customer.getByLabel('Usuário').fill('cliente1988')
  await customer.getByLabel('Senha').fill('123')
  await customer.getByRole('button', {name:'Entrar', exact:true}).click()
  await expect(customer.getByText('Café Aurora')).toBeVisible()
  const responsePromise = customer.waitForResponse(r=>r.url().endsWith('/api/chat')&&r.request().method()==='POST')
  await customer.getByLabel('Sua mensagem').fill('Will it rain tomorrow?')
  await customer.getByRole('button', {name:'Enviar mensagem'}).click()
  const response = await (await responsePromise).json()
  expect(response.route).toBe('blocked')
  expect(response.agents_used).toEqual(['Guardrail'])
  await expect(customer.getByText('I am the Getnet support assistant.', {exact:false})).toBeVisible()
  await expect(customer.locator('body')).not.toContainText('[object Object]')
  await customer.screenshot({path:'../docs/evidence/agent-policy/customer-weather-refused.png', fullPage:true})
  await context.close()
  await adminContext.close()
})
