import { expect, test } from '@playwright/test'

test.skip(!process.env.REAL_E2E, 'Requer Docker local e banco de demonstração.')

test('portais reais: cliente e técnico carregam com logo e tipografia ampliada', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } })
  const page = await context.newPage()
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const logo = async () => {
    const img = page.getByRole('img', { name: 'Getnet', exact: true })
    await expect(img).toBeVisible()
    await expect.poll(() => img.evaluate((node: HTMLImageElement) => node.naturalWidth)).toBe(887)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  }
  await page.goto('/')
  await page.getByLabel('Usuário').fill('cliente1988')
  await page.getByLabel('Senha').fill('123')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Minha conta' })).toBeVisible()
  await logo()
  await page.getByRole('link', { name: 'Minhas máquinas', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Minhas máquinas' })).toBeVisible()
  await logo()
  await page.getByRole('link', { name: 'Minha conta', exact: true }).click()
  await expect(page.getByLabel('Senha atual')).toBeVisible()
  expect(await page.getByLabel('Senha atual').evaluate(node => parseFloat(getComputedStyle(node).fontSize))).toBeGreaterThanOrEqual(16)
  await page.setViewportSize({ width: 390, height: 844 })
  await logo()
  await page.getByRole('button', { name: 'Sair', exact: true }).click()
  await page.goto('/login')
  await page.getByLabel('Usuário').fill('Tecnico')
  await page.getByLabel('Senha').fill('Tecnico')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page).toHaveURL(/\/tecnico(?:\/atendimento)?$/)
  await expect(page.getByRole('heading', { name: 'Atendimentos aguardando um técnico' })).toBeVisible()
  await logo()
  await page.getByRole('button', { name: /^Encerrados/ }).click()
  await expect(page.getByRole('heading', { name: 'Encerrados', exact: true })).toBeVisible()
  await logo()
  await page.getByRole('button', { name: /Sair/ }).click()
  expect(errors).toEqual([])
  await context.close()
})
