import {FormEvent,useEffect,useState} from 'react'
import {BookOpen,Boxes,LayoutDashboard,LogOut,Plus,ScrollText,Search,Users} from 'lucide-react'
import './admin.css'
import {KnowledgePanel} from './KnowledgePanel'
import {DashboardPanel} from './DashboardPanel'
import {LogsPanel} from './LogsPanel'
import {api,queryString} from './api'
import {CustomersPanel} from './CustomersPanel'

type User={id:number;username:string;role:'admin'|'tecnico';display_name:string;is_active:boolean;presence?:string}
type Page<T>={items:T[];total:number;page:number;page_size:number}
type Model={id:number;name:string;is_active:boolean;terminal_count:number}
type Terminal={id:string;customer_id:string;customer_name:string;model_id:number;model_name:string;status:string;last_error?:string}
type Audit={id:number;actor_name:string;action:string;entity:string;entity_id:string;diff:any;created_at:string}

export function AdminWorkspace(){
 const [me,setMe]=useState<User|null>(null),[section,setSection]=useState('users'),[error,setError]=useState(''),[ragDegraded,setRagDegraded]=useState(false)
 useEffect(()=>{api<User>('/auth/me').then(user=>{if(user.role!=='admin')throw Error();setMe(user)}).catch(()=>location.replace('/login'))},[])
 useEffect(()=>{fetch('/api/health/ready').then(r=>r.ok?r.json():null).then(status=>setRagDegraded(Boolean(status?.degraded))).catch(()=>undefined)},[])
 const logout=async()=>{await api('/auth/logout',{method:'POST'});location.assign('/login')}
 return <main className="admin-shell"><aside className="admin-nav"><div className="admin-brand">getnet<span>_</span><small>ADMIN WORKSPACE</small></div><nav>{[['dashboard',LayoutDashboard,'Dashboard'],['users',Users,'Usuários'],['customers',Users,'Clientes'],['machines',Boxes,'Máquinas'],['knowledge',BookOpen,'Base de conhecimento'],['logs',ScrollText,'Logs']] .map(([id,Icon,label]:any)=><button key={id} className={section===id?'active':''} onClick={()=>{setSection(id);setError('')}}><Icon/>{label}</button>)}</nav><div className="admin-profile"><strong>{me?.display_name}</strong><span>Administrador</span><button onClick={logout}><LogOut/> Sair</button></div></aside><section className="admin-main"><header><div><small>ADMINISTRAÇÃO</small><h1>{section==='users'?'Usuários':section==='customers'?'Clientes':section==='machines'?'Máquinas':section==='logs'?'Logs':section==='dashboard'?'Dashboard':'Base de conhecimento'}</h1></div></header>{ragDegraded&&<div className="admin-alert" role="status">Base de conhecimento indisponível ou ainda vazia. <button onClick={()=>setSection('knowledge')}>Reindexar</button></div>}{error&&<div className="admin-alert">{error}<button onClick={()=>setError('')}>×</button></div>}{section==='dashboard'?<DashboardPanel fail={setError}/>:section==='users'?<UsersPanel me={me} fail={setError}/>:section==='customers'?<CustomersPanel fail={setError}/>:section==='machines'?<MachinesPanel fail={setError}/>:section==='knowledge'?<KnowledgePanel fail={setError}/>:section==='logs'?<LogsPanel fail={setError} audit={<AuditPanel fail={setError}/>}/>:<ComingSoon/>}</section></main>
}

function UsersPanel({me,fail}:{me:User|null;fail:(s:string)=>void}){
 const [items,setItems]=useState<User[]>([]),[show,setShow]=useState(false)
 const load=()=>api<User[]>('/admin/users').then(setItems).catch(e=>fail(e.message));useEffect(()=>{void load()},[])
 const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);try{await api('/admin/users',{method:'POST',body:JSON.stringify(Object.fromEntries(form))});setShow(false);load()}catch(e){fail((e as Error).message)}}
 const edit=async(user:User)=>{const display_name=prompt('Nome de exibição:',user.display_name);if(!display_name)return;const role=prompt('Perfil (admin ou tecnico):',user.role);if(role!=='admin'&&role!=='tecnico')return;try{await api(`/admin/users/${user.id}`,{method:'PATCH',body:JSON.stringify({display_name,role})});load()}catch(e){fail((e as Error).message)}}
 const deactivate=async(user:User)=>{if(!confirm(`Desativar ${user.display_name}?`))return;try{await api(`/admin/users/${user.id}`,{method:'DELETE'});load()}catch(e){fail((e as Error).message)}}
 return <div className="admin-panel"><div className="panel-actions"><div><h2>Equipe interna</h2><p>Administradores e técnicos autorizados.</p></div><button className="primary" onClick={()=>setShow(true)}><Plus/>Novo usuário</button></div><div className="admin-table"><table><thead><tr><th>Nome</th><th>Usuário</th><th>Perfil</th><th>Presença</th><th>Status</th><th/></tr></thead><tbody>{items.map(user=><tr key={user.id}><td><strong>{user.display_name}</strong>{user.id===me?.id&&<small> Você</small>}</td><td>{user.username}</td><td>{user.role==='admin'?'Administrador':'Técnico'}</td><td>{user.presence||'—'}</td><td><span className={'pill '+(user.is_active?'success':'muted')}>{user.is_active?'Ativo':'Inativo'}</span></td><td><button onClick={()=>edit(user)}>Editar</button><button disabled={!user.is_active} onClick={()=>deactivate(user)}>Desativar</button></td></tr>)}</tbody></table></div>{show&&<div className="admin-modal"><form onSubmit={create}><button type="button" className="modal-x" onClick={()=>setShow(false)}>×</button><h2>Novo usuário</h2><label>Nome de exibição<input name="display_name" required minLength={2}/></label><label>Usuário<input name="username" required minLength={3}/></label><label>Senha<input name="password" type="password" required minLength={8}/></label><label>Perfil<select name="role"><option value="tecnico">Técnico</option><option value="admin">Administrador</option></select></label><button className="primary">Criar usuário</button></form></div>}</div>
}

function MachinesPanel({fail}:{fail:(s:string)=>void}){
 const [kind,setKind]=useState<'terminal'|'model'>('terminal'),[search,setSearch]=useState(''),[page,setPage]=useState(1),[data,setData]=useState<Page<any>>({items:[],total:0,page:1,page_size:10}),[models,setModels]=useState<Model[]>([])
 const load=()=>api<Page<any>>(`/admin/machines?${queryString({kind,search,page,page_size:10})}`).then(setData).catch(e=>fail(e.message));useEffect(()=>{void load()},[kind,page]);useEffect(()=>{api<Page<Model>>('/admin/machines?kind=model&page_size=100').then(r=>setModels(r.items)).catch(e=>fail(e.message))},[])
 const create=async()=>{try{if(kind==='model'){const name=prompt('Nome do novo modelo:');if(!name)return;await api('/admin/machines',{method:'POST',body:JSON.stringify({kind:'model',name})})}else{const id=prompt('Identificador do terminal:');const customer_id=prompt('Cliente (ex.: cliente1988):');const model_id=prompt('ID do modelo:');const status=prompt('Status inicial:','online');if(!id||!customer_id||!model_id||!status)return;await api('/admin/machines',{method:'POST',body:JSON.stringify({kind:'terminal',id,customer_id,model_id:Number(model_id),status})})}load()}catch(e){fail((e as Error).message)}}
 const edit=async(item:any)=>{try{if(kind==='model'){const name=prompt('Nome do modelo:',item.name);if(!name)return;await api(`/admin/machines/model/${item.id}`,{method:'PATCH',body:JSON.stringify({name})})}else{const customer_id=prompt('Cliente:',item.customer_id),model_id=prompt('ID do modelo:',String(item.model_id)),status=prompt('Status do terminal:',item.status);if(!customer_id||!model_id||!status)return;await api(`/admin/machines/terminal/${item.id}`,{method:'PATCH',body:JSON.stringify({customer_id,model_id:Number(model_id),status})})}load()}catch(e){fail((e as Error).message)}}
 const remove=async(item:any)=>{if(!confirm('Confirma a remoção?'))return;try{await api(`/admin/machines/${kind}/${item.id}`,{method:'DELETE'});load()}catch(e){fail((e as Error).message)}}
 return <div className="admin-panel"><div className="panel-actions"><div><h2>Parque de máquinas</h2><p>Catálogo e terminais vinculados aos clientes.</p></div><button className="primary" onClick={create}><Plus/>Novo {kind==='model'?'modelo':'terminal'}</button></div><div className="machine-tools"><div className="admin-segment"><button className={kind==='terminal'?'active':''} onClick={()=>{setKind('terminal');setPage(1)}}>Terminais</button><button className={kind==='model'?'active':''} onClick={()=>{setKind('model');setPage(1)}}>Modelos</button></div><form onSubmit={e=>{e.preventDefault();setPage(1);load()}}><Search/><input aria-label="Buscar máquinas" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar…"/></form></div><div className="admin-table"><table><thead><tr>{kind==='model'?<><th>Modelo</th><th>Ativo</th><th>Terminais</th></>:<><th>Terminal</th><th>Cliente</th><th>Modelo</th><th>Status</th></>}<th/></tr></thead><tbody>{data.items.map((item:Model|Terminal)=><tr key={item.id}>{kind==='model'?<><td><strong>{(item as Model).name}</strong></td><td>{(item as Model).is_active?'Sim':'Não'}</td><td>{(item as Model).terminal_count}</td></>:<><td><strong>{item.id}</strong></td><td>{(item as Terminal).customer_name}</td><td>{(item as Terminal).model_name}</td><td><span className="pill">{(item as Terminal).status}</span></td></>}<td><button onClick={()=>edit(item)}>Editar</button><button onClick={()=>remove(item)}>Remover</button></td></tr>)}</tbody></table></div><div className="pagination"><span>{data.total} registros</span><button disabled={page===1} onClick={()=>setPage(page-1)}>Anterior</button><button disabled={page*10>=data.total} onClick={()=>setPage(page+1)}>Próxima</button></div><div className="model-hint">Modelos disponíveis: {models.map(m=>`${m.id} — ${m.name}`).join(' · ')}</div></div>
}

function AuditPanel({fail}:{fail:(s:string)=>void}){const [data,setData]=useState<Page<Audit>>({items:[],total:0,page:1,page_size:20}),[entity,setEntity]=useState('');const load=()=>api<Page<Audit>>(`/admin/audit?${queryString({entity,page_size:50})}`).then(setData).catch(e=>fail(e.message));useEffect(()=>{void load()},[entity]);return <div className="admin-panel"><div className="panel-actions"><div><h2>Registro de auditoria</h2><p>Alterações administrativas, sem credenciais ou segredos.</p></div><select aria-label="Filtrar entidade" value={entity} onChange={e=>setEntity(e.target.value)}><option value="">Todas</option><option value="user">Usuários</option><option value="terminal">Terminais</option><option value="machine_model">Modelos</option></select></div><div className="audit-list">{data.items.map(row=><article key={row.id}><span>{new Date(row.created_at).toLocaleString('pt-BR')}</span><strong>{row.action}</strong><p>{row.actor_name||'Sistema'} · {row.entity} #{row.entity_id}</p><code>{JSON.stringify(row.diff)}</code></article>)}</div></div>}
function ComingSoon(){return <div className="coming-soon"><LayoutDashboard/><h2>Em breve</h2><p>Esta seção será implementada em uma próxima fase.</p></div>}
